# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Build Openwrt Offical

# on:
#   push:
#     paths:
#       - luci/**
#       - package/**

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: clone
        run: |
          git clone https://github.com/openwrt/openwrt.git
          pwd
          ls -al
          
