name: Build all target

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:
      openwrt_tag:
        type: string
      openwrt_master:
        type: boolean

jobs:
  setup:
    name: Setup
    runs-on: self-hosted
    outputs:
      targets: ${{ steps.find_targets.outputs.targets }}
      targets_subtargets: ${{ steps.find_targets.outputs.targets_subtargets }}
      openwrt_tag: ${{ steps.set_env.outputs.openwrt_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env
        id: set_env
        run: |
          openwrt_tag=${{ inputs.openwrt_tag }}
          [ -n "${openwrt_tag}" ] || openwrt_tag=$(curl -sL https://github.com/openwrt/openwrt | sed -n 's/.*\/openwrt\/openwrt\/releases\/tag\/\(.*\)">/\1/p')
          echo "openwrt_tag=${openwrt_tag}" >> "$GITHUB_OUTPUT"
      - name: Set targets
        id: find_targets
        run: python3 -B ./.github/workflows/scripts/get_targets.py ${{ inputs.openwrt_master && '--openwrt-master' || '' }} | while read v;do echo "$v" >> "$GITHUB_OUTPUT"; done
  
  build:
    name: Build target
    needs: setup
    strategy:
       fail-fast: false
       matrix:
         include: ${{fromJson(needs.setup.outputs.targets_subtargets)}}
    uses: ./.github/workflows/build.yml
    with:
      target: ${{ matrix.target }}
      subtarget: ${{ matrix.subtarget }}
      output_image_type: ${{ matrix.output_image_type }}
      openwrt_tag: ${{ needs.setup.outputs.openwrt_tag }}
      openwrt_master: ${{ inputs.openwrt_master }}

  set-tag:
    name: Set tag
    runs-on: self-hosted
    needs: [setup,build]
    if: ${{ ! inputs.openwrt_master }}
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          openwrt_tag=${{ needs.setup.outputs.openwrt_tag }}
          git tag ${openwrt_tag} --force
          git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY} ${openwrt_tag} --force

  release:
    name: Release target
    runs-on: self-hosted
    needs: [setup,build,set-tag]
    if: ${{ ! inputs.openwrt_master }}
    strategy:
       fail-fast: false
       matrix:
         target: ${{fromJson(needs.setup.outputs.targets)}}
    steps:
      - name: Upload to MinIO
        env: 
          MC_HOST_TARGET: http://${{ secrets.MINIO_ACCESS_KEY }}:${{ secrets.MINIO_SECRET_KEY }}@${{ secrets.MINIO_ENDPOINT }}
        run: |
          mc cp --json /data/openwrt/bin/artifact/${{ inputs.openwrt_master && 'master' || 'stable' }}/openwrt-${{ matrix.target }}-* TARGET/${{ secrets.MINIO_BUCKET }}/${{ inputs.openwrt_master && 'master' || needs.setup.outputs.openwrt_tag }}/

      - name: Upload to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.setup.outputs.openwrt_tag }}
          files: /data/openwrt/bin/artifact/stable/openwrt-${{ matrix.target }}-*