name: Build all images

on:
  workflow_dispatch:
    inputs:
      openwrt_tag:
        type: string
        description: "eg: v23.05.5"

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.get_targets.outputs.targets }}
      targets_subtargets: ${{ steps.get_targets.outputs.targets_subtargets }}
      targets_devices: ${{ steps.get_targets.outputs.targets_devices }}
      archs: ${{ steps.get_targets.outputs.archs }}
      openwrt_dir: ${{ steps.set_env.outputs.openwrt_dir }}
      openwrt_tag: ${{ steps.set_env.outputs.openwrt_tag }}
      openwrt_tag_version: ${{ steps.set_env.outputs.openwrt_tag_version }}
      openwrt_branch: ${{ steps.set_env.outputs.openwrt_branch }}
      openwrt_branch_version: ${{ steps.set_env.outputs.openwrt_branch_version }}
      openwrt_builder_volume: ${{ steps.set_env.outputs.openwrt_builder_volume }}
      artifact_targets_rel: ${{ steps.set_env.outputs.artifact_targets_rel }}
      artifact_packages_rel: ${{ steps.set_env.outputs.artifact_packages_rel }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env
        id: set_env
        run: |
          openwrt_dir=/data/openwrt
          openwrt_tag=${{ inputs.openwrt_tag }}
          openwrt_tag=${openwrt_tag:-$(curl -sL https://github.com/openwrt/openwrt | sed -n 's/.*\/openwrt\/openwrt\/releases\/tag\/\(.*\)">/\1/p')}
          openwrt_tag_version=$(echo $openwrt_tag | sed 's|^v||')
          openwrt_branch=$(echo ${openwrt_tag} | sed 's/^v\([0-9][0-9]\.[0-9][0-9]\)\..\+/openwrt-\1/')
          openwrt_branch_version=$(echo $openwrt_branch | sed 's|openwrt-||')

          echo "openwrt_dir=${openwrt_dir}" >> "$GITHUB_OUTPUT"
          echo "openwrt_tag=${openwrt_tag}" >> "$GITHUB_OUTPUT"
          echo "openwrt_tag_version=${openwrt_tag_version}" >> "$GITHUB_OUTPUT"
          echo "openwrt_branch=${openwrt_branch}" >> "$GITHUB_OUTPUT"
          echo "openwrt_branch_version=${openwrt_branch_version}" >> "$GITHUB_OUTPUT"

          openwrt_builder_volume=/volume2/storage/docker-data/openwrt-builder/data/
          echo "openwrt_builder_volume=${openwrt_builder_volume}" >> "$GITHUB_OUTPUT"

          artifact_targets_rel=releases/$openwrt_tag_version/targets
          artifact_packages_rel=releases/packages-$openwrt_branch_version
          
          echo "artifact_targets_rel=${artifact_targets_rel}" >> "$GITHUB_OUTPUT"
          echo "artifact_packages_rel=${artifact_packages_rel}" >> "$GITHUB_OUTPUT"

      - name: Get targets
        id: get_targets
        run: python3 -B ./.github/workflows/scripts/get_targets.py | while read v;do echo "$v" >> "$GITHUB_OUTPUT"; done

  build:
    name: Build
    needs: setup
    uses: ./.github/workflows/build-image.yml
    strategy:
       fail-fast: false
       matrix:
         include: ${{fromJson(needs.setup.outputs.targets_subtargets)}}
    with:
      target: ${{ matrix.target }}
      subtarget: ${{ matrix.subtarget }}
      openwrt_tag: ${{ needs.setup.outputs.openwrt_tag }}
      openwrt_tag_version: ${{ needs.setup.outputs.openwrt_tag_version }}
      openwrt_builder_volume: ${{ needs.setup.outputs.openwrt_builder_volume }}
      artifact_targets_rel: ${{ needs.setup.outputs.artifact_targets_rel }}