name: Build all packages

on:
  workflow_dispatch:
    inputs:
      openwrt_tag:
        type: string
      openwrt_master:
        type: boolean
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.get_devices.outputs.targets }}
      targets_subtargets: ${{ steps.get_devices.outputs.targets_subtargets }}
      targets_devices: ${{ steps.get_devices.outputs.targets_devices }}
      openwrt_dir: ${{ steps.set_env.outputs.openwrt_dir }}
      openwrt_tag: ${{ steps.set_env.outputs.openwrt_tag }}
      openwrt_branch: ${{ steps.set_env.outputs.openwrt_branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env
        id: set_env
        run: |
          openwrt_dir=/data/openwrt
          openwrt_tag=${{ inputs.openwrt_tag }}
          openwrt_tag=${openwrt_tag:-$(curl -sL https://github.com/openwrt/openwrt | sed -n 's/.*\/openwrt\/openwrt\/releases\/tag\/\(.*\)">/\1/p')}
          openwrt_branch=$(echo ${openwrt_tag} | sed 's/^v\([0-9][0-9]\.[0-9][0-9]\)\..\+/openwrt-\1/')

          echo "openwrt_dir=${openwrt_dir}" >> "$GITHUB_OUTPUT"
          echo "openwrt_tag=${openwrt_tag}" >> "$GITHUB_OUTPUT"
          echo "openwrt_branch=${openwrt_branch}" >> "$GITHUB_OUTPUT"

      - name: Get devices
        id: get_devices
        run: python3 -B ./.github/workflows/scripts/get_devices.py | while read v;do echo "$v" >> "$GITHUB_OUTPUT"; done
  
  build:
    name: Build
    needs: setup
    uses: ./.github/workflows/build-package.yml
    strategy:
       fail-fast: false
       matrix:
         include: ${{fromJson(needs.setup.outputs.targets_subtargets)}}
    with:
      target: ${{ matrix.target }}
      subtarget: ${{ matrix.subtarget }}
      openwrt_branch: ${{ needs.setup.outputs.openwrt_branch }}

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: [setup,build]
    strategy:
       fail-fast: false
       matrix:
         include: ${{fromJson(needs.setup.outputs.targets_subtargets)}}
    steps:
      - name: Create folder
        id: create_artifact_dir
        run: |
          artifact_dir=/data/download
          artifact_snapshot_dir=$artifact_dir/snapshots
          artifact_version_dir=$artifact_dir/releases/packages-$(echo '${{ needs.setup.outputs.openwrt_branch }}' | sed 's|openwrt-||')
          artifact_finally_dir=$artifact_version_dir
          if [ "${{ inputs.openwrt_master }}" == "true" ];then
            artifact_finally_dir=$artifact_snapshot_dir
          fi
          mkdir -p $artifact_finally_dir
          
          echo "artifact_dir=${artifact_dir}" >> "$GITHUB_OUTPUT"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.target }}-${{ matrix.subtarget }}-packages
          path: ${{ steps.outputs.create_artifact_dir }}