# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Build Openwrt Offical

on:
  # Runs on pushes targeting the default branch
  push:
    paths:
      - luci/**
      - package/**
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: init
        run: |
          sudo apt update -y
          sudo apt install -y build-essential clang flex g++ gawk gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget qemu-utils libelf-dev vim git make gcc
      - name: clone
        env:
          OPENWRT_TAG: v22.03.5
          OPENWRT_FEED_BRANCH: openwrt-22.03
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          git checkout ${OPENWRT_TAG}
          sed -i -e 's|\^.*|;${OPENWRT_FEED_BRANCH}|' feeds.conf.default
          echo "
          src-git helloworld https://github.com/fw876/helloworld
          src-git plugin https://github.com/czy21/openwrt-plugin.git
          " >> feeds.conf.default
      - name: update
        working-directory: openwrt
        run: |
          ./scripts/feeds update -a 
          ./scripts/feeds install -a
          ./feeds/plugin/sync.sh
          ls -al
          ls -al openwrt
          
