name: Build x86 target

on:
  push:
    paths:
      - config/x86/**

jobs:
  build_ext:
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        subtarget: [64]
    with:
      target: x86
      subtarget: ${{ matrix.subtarget }}
      output_image_type: combined-efi