name: Build x86 target

on:
  push:
    paths:
      - config/x86/**
  workflow_dispatch:
    inputs:
      first_build:
        required: true
        default: false
        type: boolean

jobs:
  build_ext:
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        subtarget: [64]
    with:
      target: x86
      subtarget: ${{ matrix.subtarget }}
      first_build: ${{ inputs.first_build }}
      output_image_type: combined-efi