name: Build all stable

on:
  schedule:
    # 每周月一号零点
    - cron: '0 0 1 * *'

  workflow_dispatch:
    inputs:
      openwrt_tag:
        type: string

jobs:
  setup:
    name: Setup
    runs-on: self-hosted
    outputs:
      targets: ${{ steps.get_targets.outputs.targets }}
      targets_subtargets: ${{ steps.get_targets.outputs.targets_subtargets }}
      openwrt_dir: ${{ steps.set_env.outputs.openwrt_dir }}
      openwrt_tag: ${{ steps.set_env.outputs.openwrt_tag }}
      openwrt_branch: ${{ steps.set_env.outputs.openwrt_branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set env
        id: set_env
        run: |
          openwrt_dir=/data/openwrt
          openwrt_tag=${{ inputs.openwrt_tag }}
          openwrt_tag=${openwrt_tag:-$(curl -sL https://github.com/openwrt/openwrt | sed -n 's/.*\/openwrt\/openwrt\/releases\/tag\/\(.*\)">/\1/p')}
          openwrt_branch=$(echo ${openwrt_tag} | sed 's/^v\([0-9][0-9]\.[0-9][0-9]\)\..\+/openwrt-\1/')

          echo "openwrt_dir=${openwrt_dir}" >> "$GITHUB_OUTPUT"
          echo "openwrt_tag=${openwrt_tag}" >> "$GITHUB_OUTPUT"
          echo "openwrt_branch=${openwrt_branch}" >> "$GITHUB_OUTPUT"
      - name: Get targets
        id: get_targets
        run: python3 -B ./.github/workflows/scripts/get_targets.py | while read v;do echo "$v" >> "$GITHUB_OUTPUT"; done
  
  build:
    name: Build
    needs: setup
    uses: ./.github/workflows/build.yml
    secrets: inherit
    strategy:
       fail-fast: false
       matrix:
         include: ${{fromJson(needs.setup.outputs.targets_subtargets)}}
    with:
      target: ${{ matrix.target }}
      subtarget: ${{ matrix.subtarget }}
      output_image_type: ${{ matrix.output_image_type }}
      openwrt_tag: ${{ needs.setup.outputs.openwrt_tag }}

  post:
    name: Post
    runs-on: self-hosted
    needs: [setup,build]
    steps:
      - name: Set tag
        run: |
          git tag ${{ needs.setup.outputs.openwrt_tag }} --force
          git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY} refs/tags/${{ needs.setup.outputs.openwrt_tag }} --force

  release:
    name: Release
    runs-on: self-hosted
    needs: [setup,build,post]
    strategy:
       fail-fast: false
       matrix:
         target: ${{fromJson(needs.setup.outputs.targets)}}
    steps:
      - name: Upload to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.setup.outputs.openwrt_tag }}
          files: ${{ needs.setup.outputs.openwrt_dir }}/bin/artifact/openwrt-${{ matrix.target }}-*