name: Build latest stable tag

on:
  workflow_dispatch:

env:
  openwrt_workdir: /data/openwrt

jobs:
  setup:
    name: Setup
    runs-on: self-hosted
    outputs:
      targets: ${{ steps.find_targets.outputs.targets }}
      targets_subtargets: ${{ steps.find_targets.outputs.targets_subtargets }}
      openwrt_tag: ${{ steps.get_latest_stable.outputs.openwrt_tag }}
      openwrt_branch: ${{ steps.get_latest_stable.outputs.openwrt_branch }}
    steps:
      - name: Get latest stable tag
        id: get_latest_stable
        run: |
          openwrt_tag=$(curl -s https://api.github.com/repos/openwrt/openwrt/releases/latest | sed -n '/tag_name/p' | sed 's|^\s*"tag_name": "\(.*\)",|\1|')
          if [[ "${openwrt_tag}" =~ ^v[0-9] ]];then
            openwrt_branch=$(echo ${openwrt_tag} | sed 's|^v\([0-9]\+\.[0-9]\+\).*|openwrt-\1|')
            echo "openwrt_tag=${openwrt_tag}" >> "$GITHUB_OUTPUT"
            echo "openwrt_branch=${openwrt_branch}" >> "$GITHUB_OUTPUT"
          else
            echo "error: get latest stable tag fail"
            exit 1
          fi
      - name: Check branch
        run: | 
          remote_branch=`git ls-remote https://github.com/czy21/openwrt-plugin | grep 'refs/heads/${{ steps.get_latest_stable.outputs.openwrt_branch }}'`
          
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set targets
        id: find_targets
        run: python3 -B .github/workflows/scripts/get_targets.py | while read v;do echo "$v" >> "$GITHUB_OUTPUT"; done

      - name: Checkout Openwrt
        run: |
          openwrt_tag=${{ steps.get_latest_stable.outputs.openwrt_tag }}
          openwrt_branch=${{ steps.get_latest_stable.outputs.openwrt_branch }}
          openwrt_dir_tag=
          if [ -d ${{ env.openwrt_workdir }}/.git ];then
            openwrt_dir_tag=`cd ${{ env.openwrt_workdir }} && git tag --points-at HEAD`
          fi
          if [ "${openwrt_tag}" != "${openwrt_dir_tag}" ];then
            rm -rf ${{ env.openwrt_workdir }}
            git clone http://gitea.czy21-internal.com/openwrt/openwrt.git ${{ env.openwrt_workdir }}
          fi
          cd ${{ env.openwrt_workdir }} && git checkout --force ${openwrt_tag}
          sed -i -e 's|https://git.openwrt.org/\(.*\)/|http://gitea.czy21-internal.com/openwrt/|g' -e "s|\^.*|;${openwrt_branch}|" feeds.conf.default
          echo "
          src-git helloworld https://github.com/fw876/helloworld
          src-git plugin https://github.com/czy21/openwrt-plugin.git;${openwrt_branch}
          " >> feeds.conf.default
  
  build:
    name: Build target
    needs: setup
    strategy:
       fail-fast: false
       matrix:
         include: ${{fromJson(needs.setup.outputs.targets_subtargets)}}
    uses: ./.github/workflows/build.yml
    with:
      target: ${{ matrix.target }}
      subtarget: ${{ matrix.subtarget }}
      output_image_type: ${{ matrix.output_image_type }}
  
  # release:
  #   name: Release to github
  #   needs: build
  #   steps:
  #     - name: Set tag
  #       run: |
  #         git pull 
  #         git tag ${{ needs.setup.outputs.openwrt_tag }} --force

  #         git push --tag --force
  #     - uses: softprops/action-gh-release@v1
  #       if: startsWith(${{ needs.setup.outputs.openwrt_tag }}, 'refs/tags/')
  #       with:
  #         files: ${{ openwrt_workdir }}/artifact/** 