name: Build all master

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: self-hosted
    outputs:
      targets: ${{ steps.get_targets.outputs.targets }}
      targets_subtargets: ${{ steps.get_targets.outputs.targets_subtargets }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get targets
        id: get_targets
        run: python3 -B ./.github/workflows/scripts/get_targets.py --openwrt-master | while read v;do echo "$v" >> "$GITHUB_OUTPUT"; done
  
  build:
    name: Build
    needs: setup
    uses: ./.github/workflows/build.yml
    secrets: inherit
    strategy:
       fail-fast: false
       matrix:
         include: ${{fromJson(needs.setup.outputs.targets_subtargets)}}
    with:
      target: ${{ matrix.target }}
      subtarget: ${{ matrix.subtarget }}
      output_image_type: ${{ matrix.output_image_type }}
      openwrt_master: true