name: Build all master

on:
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: self-hosted
    outputs:
      targets: ${{ steps.get_targets.outputs.targets }}
      targets_devices: ${{ steps.get_targets.outputs.targets_devices }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get targets
        id: get_targets
        run: python3 -B ./.github/workflows/scripts/get_targets.py --openwrt-master | while read v;do echo "$v" >> "$GITHUB_OUTPUT"; done
  
  build:
    name: Build
    needs: setup
    uses: ./.github/workflows/build.yml
    strategy:
       fail-fast: false
       matrix:
         include: ${{fromJson(needs.setup.outputs.targets_devices)}}
    with:
      target: ${{ matrix.target }}
      device: ${{ matrix.device }}
      device_image_type: ${{ matrix.device_image_type }}
      openwrt_master: true