name: Build rockchip target

on:
  workflow_dispatch:
    inputs:
      first_build:
        required: true
        default: false
        type: boolean

jobs:
  build_ext:
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        subtarget: [r2s,r4s]
    with:
      target: rockchip
      subtarget: ${{ matrix.subtarget }}
      first_build: ${{ inputs.first_build }}