name: Checkout openwrt tag

on:
  workflow_dispatch:
    inputs:
      openwrt_tag:
        required: true
        default: 'v22.03.5'
        type: choice
        options:
          - v22.03.5
  
jobs:
  set_target:
    name: Set targets
    runs-on: self-hosted
    outputs:
      targets_subtargets: ${{ steps.find_targets.outputs.targets_subtargets }}
      targets: ${{ steps.find_targets.outputs.targets }}
    steps:
      - name: Checkout
        working-directory: /data/openwrt-dev
        run: |
          cloned=`git ls-remote ${{ github.workspace }} -q 2>/dev/null && echo true || echo false`
          [ "${cloned}" == false ] && git clone http://gitea.czy21-internal.com/openwrt/openwrt.git ${{ github.workspace }}
          [  "${{ inputs.openwrt_tag }}" != "`git tag --points-at HEAD`" ] && `git checkout --force ${{ inputs.openwrt_tag }}`
          openwrt_branch=`git branch -a --contains v19.07.9 2>/dev/null| sed -n '/remotes\/origin/p' | sed -e 's|^\s*remotes/origin/||'`
          [ -n "${openwrt_branch}" ] && sed -i -e 's|https://git.openwrt.org/\(.*\)/|http://gitea.czy21-internal.com/openwrt/|g' -e "s|\^.*|;${openwrt_branch}|" feeds.conf.default
          echo "
          src-git helloworld https://github.com/fw876/helloworld
          src-git plugin https://github.com/czy21/openwrt-plugin.git
          " >> feeds.conf.default
      - name: Set targets
        id: find_targets
        run: |
          echo "find targets workflow"
  
  # build:
  #   name: Build targets
  #   needs: set_target
  #   strategy:
  #      fail-fast: false
  #      matrix:
  #        include: ${{fromJson(needs.set_target.outputs.targets_subtargets)}}
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     target: ${{ matrix.target }}
  #     subtarget: ${{ matrix.subtarget }}
  #     output_image_type: ${{ matrix.output_image_type }}