name: Checkout openwrt tag

on:
  workflow_dispatch:
    inputs:
      openwrt_tag:
        required: true
        default: 'v22.03.5'
        type: choice
        options:
          - v22.03.5
env:
  openwrt_workdir: /data/openwrt-dev

jobs:
  set_target:
    name: Set targets
    runs-on: self-hosted
    outputs:
      targets: ${{ steps.find_targets.outputs.targets }}
      targets_subtargets: ${{ steps.find_targets.outputs.targets_subtargets }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set targets
        id: find_targets
        run: |
          python3 -B function/get_targets.py | while read v;do echo "$v" >> "$GITHUB_OUTPUT"; done
      - name: Checkout Openwrt
        run: |
          cloned=`git ls-remote ${{ env.openwrt_workdir }} -q 2>/dev/null && echo true || echo false`
          [ "${cloned}" == false ] && git clone http://gitea.czy21-internal.com/openwrt/openwrt.git ${{ env.openwrt_workdir }}
          cd ${{ env.openwrt_workdir }} && git checkout feeds.conf.default
          [  "${{ inputs.openwrt_tag }}" != "`git tag --points-at HEAD`" ] && `git checkout --force ${{ inputs.openwrt_tag }}`
          openwrt_branch=`git branch -a --contains ${{ inputs.openwrt_tag }} 2>/dev/null| sed -n '/remotes\/origin/p' | sed -e 's|^\s*remotes/origin/||'`
          [ -n "${openwrt_branch}" ] && sed -i -e 's|https://git.openwrt.org/\(.*\)/|http://gitea.czy21-internal.com/openwrt/|g' -e "s|\^.*|;${openwrt_branch}|" feeds.conf.default
          echo "
          src-git helloworld https://github.com/fw876/helloworld
          src-git plugin https://github.com/czy21/openwrt-plugin.git
          " >> feeds.conf.default
  
  build:
    name: Build targets
    needs: set_target
    strategy:
       fail-fast: false
       matrix:
         include: ${{fromJson(needs.set_target.outputs.targets_subtargets)}}
    uses: ./.github/workflows/build.yml
    with:
      target: ${{ matrix.target }}
      subtarget: ${{ matrix.subtarget }}
      output_image_type: ${{ matrix.output_image_type }}