name: Build check target specified in labels
on:
  pull_request:
    types:
      - labeled

jobs:
  set_target:
    if: startsWith(github.event.label.name, 'ci:target:')
    name: Set target
    runs-on: self-hosted
    outputs:
      target: ${{ steps.set_target.outputs.target }}
      subtarget: ${{ steps.set_target.outputs.subtarget }}

    steps:
      - name: Set target
        id: set_target
        env:
          CI_EVENT_LABEL_NAME: ${{ github.event.label.name }}
        run: |
          echo "=================="