on:
  workflow_dispatch:
    inputs:
      target:
        required: true
        default: 'x86-64'
        type: choice
        options:
          - x86-64
          - r4s
          - r2s
      first_build:
        required: true
        default: false
        type: boolean

jobs:
  build_target:
    use: ./.github/workflows/build.yml
    with: 
      target: ${{ inputs.target }}