name: Deploy static

on:
  push:
    paths:
      - 'static/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: openwrt/imagebuilder:x86-64-main
      volumes:
        - openwrt-share:/data/
      options: --user root --privileged --pull always
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout firmware-selector-openwrt-org
        uses: actions/checkout@v6
        with: 
          repository: openwrt/firmware-selector-openwrt-org
          path: feeds/firmware-selector-openwrt-org
          ref: "v5.1.0"

      - name: Deploy firmware-selector-openwrt-org to local
        run: |
          mkdir -p /data/firmware/
          cp -rv feeds/firmware-selector-openwrt-org/www/* /data/firmware/
          cp -rv static/firmware/* /data/firmware/
          sed -i "s;%GIT_VERSION%;$(git describe --tags);" /data/firmware/js/main.js

      - name: Checkout openwrt-download-page
        uses: actions/checkout@v6
        with: 
          repository: aparcar/openwrt-download-page
          path: feeds/openwrt-download-page
       
      - name: Deploy openwrt-download-page to local
        run: cp -rv feeds/openwrt-download-page/dir-index.cgi /data/download/