name: Deploy static content to Pages

on:
  push:
    paths:
      - 'static/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout firmware-selector-openwrt-org
        uses: actions/checkout@v4
        with: 
          repository: openwrt/firmware-selector-openwrt-org
          path: firmware-selector-openwrt-org
      
      - name: Setup config.json
        run: |
          cp -rv static/firmware/* firmware-selector-openwrt-org/www/
          sed -i "s;%GIT_VERSION%;$(git describe --tags);" firmware-selector-openwrt-org/www/index.js
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: static
          path: firmware-selector-openwrt-org/www/index.js

      - name: Deploy to local
        run: cp -rv firmware-selector-openwrt-org/www/* /data/firmware/
