name: Sync code

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - main
          - openwrt-23.05
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Determine branch
        run: |
          openwrt_branch="${GITHUB_REF#refs/heads/}"
          echo ${openwrt_branch}
          bash main.sh update

      - name: Determine changes
        run: |
          if [ -n "$(git status -s)" ];then
            git pull && git add . && git commit -m "CI: sync code" && git push
          fi