name: Build mediatek

on:
  workflow_dispatch:

jobs:
  build_ext:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        master_device: [filogic-360t7]
    with:
      target: mediatek
      device: ${{ matrix.master_device }}
      device_image_type: squashfs-sysupgrade
      openwrt_master: true