name: Build mediatek

on:
  workflow_dispatch:
    inputs:
      openwrt_tag:
        type: string

jobs:
  build_ext:
    uses: ./.github/workflows/build.yml
    strategy:
      fail-fast: false
      matrix:
        stable_device: [filogic-360t7]
    with:
      target: mediatek
      device: ${{ matrix.stable_device }}
      openwrt_tag: ${{ inputs.openwrt_tag }}