name: Build sunxi

on:
  workflow_dispatch:
    inputs:
      openwrt_tag:
        type: string
      openwrt_master:
        type: boolean

jobs:
  build_ext:
    uses: ./.github/workflows/build.yml
    strategy:
      fail-fast: false
      matrix:
        stable_subtarget: [cortexa7]
        master_subtarget: [cortexa53]
    with:
      target: sunxi
      subtarget: ${{ inputs.openwrt_master && matrix.master_subtarget || matrix.stable_subtarget }}
      output_image_type: squashfs-sdcard
      openwrt_tag: ${{ inputs.openwrt_tag }}
      openwrt_master: ${{ inputs.openwrt_master }}