name: Build x86

on:
  workflow_dispatch:
    inputs:
      openwrt_tag:
        type: string

jobs:
  build_ext:
    uses: ./.github/workflows/build.yml
    strategy:
      fail-fast: false
      matrix:
        stable_subtarget: [64]
    with:
      target: x86
      subtarget: ${{ matrix.stable_subtarget }}
      output_image_type: squashfs-combined-efi
      openwrt_tag: ${{ inputs.openwrt_tag }}