name: Build rockchip

on:
  workflow_dispatch:
    inputs:
      openwrt_tag:
        type: string
      openwrt_master:
        type: boolean

jobs:
  build_ext:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        stable_subtarget: [armv8]
        master_subtarget: [armv8]
    with:
      target: rockchip
      subtarget: ${{ inputs.openwrt_master && matrix.master_subtarget || matrix.stable_subtarget }}
      output_image_type: squashfs-sysupgrade
      openwrt_tag: ${{ inputs.openwrt_tag }}
      openwrt_master: ${{ inputs.openwrt_master }}