name: Build ramips

on:
  workflow_dispatch:
    inputs:
      openwrt_tag:
        type: string

jobs:
  build_ext:
    uses: ./.github/workflows/build.yml
    strategy:
      fail-fast: false
      matrix:
        stable_device: [mt7621-newifi-d2]
    with:
      target: ramips
      device: ${{ matrix.stable_device }}
      device_image_type: squashfs-sysupgrade
      openwrt_tag: ${{ inputs.openwrt_tag }}