name: Build rockchip

on:
  workflow_dispatch:
    inputs:
      openwrt_tag:
        type: string
      openwrt_master:
        type: boolean

jobs:
  build_ext:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        stable_device: [armv8,armv8-r2s]
        master_device: [armv8]
    with:
      target: rockchip
      device: ${{ inputs.openwrt_master && matrix.master_device || matrix.stable_device }}
      device_image_type: squashfs-sysupgrade
      openwrt_tag: ${{ inputs.openwrt_tag }}
      openwrt_master: ${{ inputs.openwrt_master }}