name: Build rockchip target

on:
  workflow_dispatch:
    inputs:
      openwrt_tag:
        type: string
      openwrt_master:
        type: boolean

env:
  stable_subtarget:
    - multi
  master_subtarget:
    - multi

jobs:
  build_ext:
    uses: ./.github/workflows/build.yml
    strategy:
      fail-fast: false
      matrix:
        subtarget: ${{ inputs.openwrt_master && env.master_subtarget || stable_subtarget }}
    with:
      target: rockchip
      subtarget: ${{ matrix.subtarget }}
      output_image_type: squashfs-sysupgrade
      openwrt_tag: ${{ inputs.openwrt_tag }}
      openwrt_master: ${{ inputs.openwrt_master }}