name: Build bcm27xx

on:
  workflow_dispatch:

jobs:
  build_ext:
    uses: ./.github/workflows/build.yml
    
    strategy:
      fail-fast: false
      matrix:
        master_device: [bcm2710]
    with:
      target: bcm27xx
      device: ${{ matrix.master_device }}
      device_image_type: squashfs-sysupgrade
      openwrt_master: true