name: Build sunxi

on:
  workflow_dispatch:

jobs:
  build_ext:
    uses: ./.github/workflows/build.yml
    strategy:
      fail-fast: false
      matrix:
        master_subtarget: [cortexa53]
    with:
      target: sunxi
      subtarget: ${{ matrix.master_subtarget }}
      output_image_type: squashfs-sdcard
      openwrt_master: true