name: Build x86 target

on:
  push:
    paths:
      - .github/workflows/build.yml
      - .github/workflows/target-x86.yml
      - config/x86/**
      - luci/**
      - package/**

jobs:
  build_ext:
    uses: ./.github/workflows/build.yml
    strategy:
      fail-fast: false
      matrix:
        subtarget: [64]
    with:
      target: x86
      subtarget: ${{ matrix.subtarget }}
      output_image_type: combined-efi