name: Build test

on:
  workflow_dispatch:

permissions:
  contents: read
  
defaults:
  run:
    shell: bash
  
jobs:
  setup:
    name: Setup 
    runs-on: self-hosted
    steps:
      - name: Set env
        id: set_env
        run: |
          echo $(cd;pwd)
          echo "=========="